#!/usr/bin/env python3
"""
Run a sequence of experiment YAML files through inference.py.

This script executes multiple YAML configuration files in sequence, typically
generated by generate_frame_sequences.py, through the inference pipeline.

Usage:
    python run_frame_sequences.py --config-dir configs/exp/sequences
    python run_frame_sequences.py --config-dir configs/exp/sequences --pattern "goprotest_tiny_frames_*.yaml"
    python run_frame_sequences.py --config-file configs/exp/sequences/goprotest_tiny_frames_0001-0010.yaml
    python run_frame_sequences.py --config-dir configs/exp/sequences --start 3 --end 7
"""

import argparse
import subprocess
import sys
from pathlib import Path
from typing import List, Optional
import time
from datetime import datetime


def find_yaml_files(config_dir: Path, pattern: str = "*.yaml") -> List[Path]:
    """Find all YAML files in the specified directory matching the pattern."""
    yaml_files = sorted(config_dir.glob(pattern))
    # Filter out summary files
    yaml_files = [f for f in yaml_files if 'summary' not in f.name]
    return yaml_files


def run_inference(config_file: Path, inference_script: Path = None, extra_args: List[str] = None) -> bool:
    """
    Run inference.py with the specified config file.
    
    Args:
        config_file: Path to the YAML config file
        inference_script: Path to inference.py (default: ./inference.py)
        extra_args: Additional arguments to pass to inference.py
    
    Returns:
        True if successful, False otherwise
    """
    if inference_script is None:
        inference_script = Path("inference.py")
    
    # Build the command
    # Use hydra override syntax: --config-path and --config-name
    config_dir = config_file.parent.absolute()
    config_name = config_file.stem  # filename without extension
    
    cmd = [
        sys.executable,
        str(inference_script),
        #f"--config-path={config_dir}",
        f"exp={config_name}",
        f"data.data_dir=./data",
    ]
    
    if extra_args:
        cmd.extend(extra_args)
    
    print(f"\n{'='*80}")
    print(f"Running: {' '.join(cmd)}")
    print(f"{'='*80}\n")
    
    try:
        result = subprocess.run(
            cmd,
            check=True,
            text=True,
            cwd=Path.cwd()
        )
        return result.returncode == 0
    except subprocess.CalledProcessError as e:
        print(f"Error running inference for {config_file.name}: {e}", file=sys.stderr)
        return False
    except KeyboardInterrupt:
        print("\nInterrupted by user")
        raise


def run_sequence(
    config_files: List[Path],
    inference_script: Path = None,
    extra_args: List[str] = None,
    continue_on_error: bool = False,
    log_file: Optional[Path] = None
) -> dict:
    """
    Run inference for a sequence of config files.
    
    Args:
        config_files: List of YAML config files to process
        inference_script: Path to inference.py
        extra_args: Additional arguments for inference.py
        continue_on_error: Whether to continue if an experiment fails
        log_file: Path to log file for tracking progress
    
    Returns:
        Dictionary with execution statistics
    """
    stats = {
        'total': len(config_files),
        'successful': 0,
        'failed': 0,
        'skipped': 0,
        'failed_files': [],
        'start_time': datetime.now()
    }
    
    # Setup logging
    if log_file:
        log_file.parent.mkdir(parents=True, exist_ok=True)
        log_handle = open(log_file, 'a')
        log_handle.write(f"\n{'='*80}\n")
        log_handle.write(f"Sequence started at: {stats['start_time']}\n")
        log_handle.write(f"Total experiments: {stats['total']}\n")
        log_handle.write(f"{'='*80}\n\n")
    else:
        log_handle = None
    
    try:
        for i, config_file in enumerate(config_files, 1):
            print(f"\n[{i}/{stats['total']}] Processing: {config_file.name}")
            
            if log_handle:
                log_handle.write(f"[{i}/{stats['total']}] {config_file.name} - Started at {datetime.now()}\n")
                log_handle.flush()
            
            experiment_start = time.time()
            success = run_inference(config_file, inference_script, extra_args)
            experiment_time = time.time() - experiment_start
            
            if success:
                stats['successful'] += 1
                status = "SUCCESS"
            else:
                stats['failed'] += 1
                stats['failed_files'].append(config_file.name)
                status = "FAILED"
                
                if not continue_on_error:
                    print(f"\nExperiment failed. Stopping sequence.")
                    if log_handle:
                        log_handle.write(f"  Status: {status} - Stopping sequence\n")
                    break
            
            print(f"\nExperiment {status} (took {experiment_time:.2f}s)")
            
            if log_handle:
                log_handle.write(f"  Status: {status} (took {experiment_time:.2f}s)\n")
                log_handle.flush()
    
    except KeyboardInterrupt:
        print("\n\nSequence interrupted by user")
        stats['skipped'] = stats['total'] - stats['successful'] - stats['failed']
    
    finally:
        stats['end_time'] = datetime.now()
        stats['total_time'] = (stats['end_time'] - stats['start_time']).total_seconds()
        
        # Print summary
        print(f"\n{'='*80}")
        print("EXECUTION SUMMARY")
        print(f"{'='*80}")
        print(f"Total experiments: {stats['total']}")
        print(f"Successful: {stats['successful']}")
        print(f"Failed: {stats['failed']}")
        print(f"Skipped: {stats['skipped']}")
        print(f"Total time: {stats['total_time']:.2f}s ({stats['total_time']/60:.2f} minutes)")
        
        if stats['failed_files']:
            print(f"\nFailed experiments:")
            for fname in stats['failed_files']:
                print(f"  - {fname}")
        
        # Write summary to log
        if log_handle:
            log_handle.write(f"\n{'='*80}\n")
            log_handle.write("EXECUTION SUMMARY\n")
            log_handle.write(f"{'='*80}\n")
            log_handle.write(f"Total experiments: {stats['total']}\n")
            log_handle.write(f"Successful: {stats['successful']}\n")
            log_handle.write(f"Failed: {stats['failed']}\n")
            log_handle.write(f"Skipped: {stats['skipped']}\n")
            log_handle.write(f"Total time: {stats['total_time']:.2f}s ({stats['total_time']/60:.2f} minutes)\n")
            log_handle.write(f"Ended at: {stats['end_time']}\n")
            if stats['failed_files']:
                log_handle.write(f"\nFailed experiments:\n")
                for fname in stats['failed_files']:
                    log_handle.write(f"  - {fname}\n")
            log_handle.close()
    
    return stats


def main():
    parser = argparse.ArgumentParser(
        description="Run a sequence of experiment YAML files through inference.py"
    )
    
    # Input methods (mutually exclusive)
    input_group = parser.add_mutually_exclusive_group(required=True)
    input_group.add_argument(
        '--config-dir',
        type=str,
        help='Directory containing experiment YAML files'
    )
    input_group.add_argument(
        '--config-file',
        type=str,
        help='Single config file to run'
    )
    
    parser.add_argument(
        '--pattern',
        type=str,
        default='*_frames_*.yaml',
        help='Glob pattern for YAML files (default: *_frames_*.yaml)'
    )
    parser.add_argument(
        '--inference-script',
        type=str,
        default='inference.py',
        help='Path to inference.py (default: inference.py)'
    )
    parser.add_argument(
        '--continue-on-error',
        action='store_true',
        help='Continue processing remaining experiments if one fails'
    )
    parser.add_argument(
        '--log-file',
        type=str,
        default='logs/sequence_execution.log',
        help='Log file for tracking progress (default: logs/sequence_execution.log)'
    )
    parser.add_argument(
        '--extra-args',
        type=str,
        nargs='*',
        help='Additional arguments to pass to inference.py'
    )
    parser.add_argument(
        '--start',
        type=int,
        default=None,
        help='1-based start index of experiments to run (inclusive)'
    )
    parser.add_argument(
        '--end',
        type=int,
        default=None,
        help='1-based end index of experiments to run (inclusive)'
    )
    
    args = parser.parse_args()
    
    # Find config files
    if args.config_file:
        config_files = [Path(args.config_file)]
        if not config_files[0].exists():
            print(f"Error: Config file not found: {args.config_file}")
            return 1
    else:
        config_dir = Path(args.config_dir)
        if not config_dir.exists():
            print(f"Error: Config directory not found: {config_dir}")
            return 1
        
        config_files = find_yaml_files(config_dir, args.pattern)
        if not config_files:
            print(f"Error: No YAML files found matching pattern '{args.pattern}' in {config_dir}")
            return 1

        # Apply start/end index slicing if provided
        if args.start is not None or args.end is not None:
            total = len(config_files)
            start = args.start if args.start is not None else 1
            end = args.end if args.end is not None else total

            # Validate indices: 1-based inclusive
            if start < 1:
                print(f"Error: --start must be >= 1 (got {start})")
                return 1
            if end < 1:
                print(f"Error: --end must be >= 1 (got {end})")
                return 1
            if start > end:
                print(f"Error: --start ({start}) must be <= --end ({end})")
                return 1
            if start > total:
                print(f"Error: --start ({start}) exceeds total experiments ({total})")
                return 1
            if end > total:
                print(f"Error: --end ({end}) exceeds total experiments ({total})")
                return 1

            # Slice using 0-based indices
            config_files = config_files[start - 1:end]
            print(f"Applied index range: start={start}, end={end} -> {len(config_files)} experiment(s)")
    
    print(f"Found {len(config_files)} experiment(s) to run:")
    for i, f in enumerate(config_files, 1):
        print(f"  {i}. {f.name}")
    
    # Confirm before starting
    try:
        response = input("\nProceed? [Y/n]: ").strip().lower()
        if response and response != 'y':
            print("Cancelled.")
            return 0
    except KeyboardInterrupt:
        print("\nCancelled.")
        return 0
    
    # Run the sequence
    inference_script = Path(args.inference_script)
    log_file = Path(args.log_file) if args.log_file else None
    
    stats = run_sequence(
        config_files=config_files,
        inference_script=inference_script,
        extra_args=args.extra_args,
        continue_on_error=args.continue_on_error,
        log_file=log_file
    )
    
    # Return exit code based on success
    if stats['failed'] > 0:
        return 1
    return 0


if __name__ == '__main__':
    exit(main())
